<a href="https://colab.research.google.com/github/MIGAYABENHUR-VIT/LearningPytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating Tensors

Created using `torch.tensor()` 

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Tensor representation of n-dim

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)


### Random Tensor

Why random Tensor?

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
#Create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3453, 0.0577, 0.2169, 0.8458],
        [0.7488, 0.8525, 0.9908, 0.9241],
        [0.4200, 0.0159, 0.7432, 0.1482]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

##Zeros and onces

In [23]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

##Creating a range of tensors and tensors-like

In [31]:
#Use torch.range()
torch.arange(0,10),torch.range(0,10)

<ipython-input-31-ba6ab4e76063>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.arange(0,10),torch.range(0,10)


(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [36]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor Datatype


In [41]:
#Flot 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what data type is the tensor
                               device=None, #example is cuda (GPU/TPU)
                               requires_grad=False #tracking gradients,wheather or not they need grad)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_32_tensor.dtype

torch.float16

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)