<a href="https://colab.research.google.com/github/MIGAYABENHUR-VIT/LearningPytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [2]:
!nvidia-smi

Tue May 16 22:22:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

### Creating Tensors

Created using `torch.tensor()` 

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Tensor representation of n-dim

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)


### Random Tensor

Why random Tensor?

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
#Create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7008, 0.9966, 0.1558, 0.2793],
        [0.0575, 0.0522, 0.2946, 0.1895],
        [0.6815, 0.6826, 0.0575, 0.0155]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

##Zeros and onces

In [21]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

##Creating a range of tensors and tensors-like

In [24]:
#Use torch.range()
torch.arange(0,10),torch.range(0,10)

<ipython-input-24-ba6ab4e76063>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.arange(0,10),torch.range(0,10)


(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [25]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor Datatype


In [27]:
#Flot 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what data type is the tensor
                               device=None, #example is cuda (GPU/TPU)
                               requires_grad=False #tracking gradients,wheather or not they need grad
                               )
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from the tensor

1.datatype - `tensor.dtype`

2.shape - `tensor.shape`

3.Device - `tensor.device`


In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8701, 0.2040, 0.6445, 0.3544],
        [0.2506, 0.3777, 0.6877, 0.9767],
        [0.6755, 0.4239, 0.4272, 0.5771]])

In [34]:
#Find details about some tensor

print("Some tensors datatype is",some_tensor.dtype)
print("some tensor's Shape is",some_tensor.shape)
print("some tensor's device is",some_tensor.device)

Some tensors datatype is torch.float32
some tensor's Shape is torch.Size([3, 4])
some tensor's device is cpu


### Manipulating tensors (tensors Operation)

Tensors operation include:


*   Addition
*   Subtraction
*   Multiplication (element wise)
*   Division
*   Matrix Multiplication

In [35]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor +  100

tensor([101, 102, 103])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor * tensor

tensor([1, 4, 9])

In [38]:
#Pytorch built-in function
torch.add(tensor,10),torch.mul(tensor,10),torch.sub(tensor,1),torch.div(tensor,2)

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([0, 1, 2]),
 tensor([0.5000, 1.0000, 1.5000]))

### There are 2 types od multiplication in NN/DL
1. Element wise
2. Matrix Multiplication (dot product)

In [39]:
print(tensor,'*',tensor,'is',tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) is tensor([1, 4, 9])


In [40]:
torch.matmul(tensor,tensor)

tensor(14)

##### Calucate the time difference b/w in-built function and user defined function

In [41]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 333 µs, sys: 46 µs, total: 379 µs
Wall time: 388 µs


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 90 µs, sys: 13 µs, total: 103 µs
Wall time: 64.6 µs


tensor(14)

### Matrix Multiplication rules
1. **Inner dimention** must match
* `(3,2) @ (3,2)` will not work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. Resulting Matrix has the shape of **outer dimention**
* `(2,3) @ (3,2)` -> `(2,2)`


In [43]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7832, 0.5311],
        [0.8441, 0.5531]])

### Matrix Error

In [44]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

print('tensor_A @ tensor_B') #This will give an error because there inner dimensions are not same

tensor_A @ tensor_B


In [45]:
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

## Finding the max,mean,sum,etc(tensor aggregation)

In [46]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [48]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [49]:
y = x.type(torch.float32)
torch.mean(y)

tensor(45.)

In [50]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##Find the positional min and max

In [51]:
x.argmin()

tensor(0)

In [52]:
x.argmax()

tensor(9)

## Reshaping,stacking,squeezing and unsqueezing tensors

* Reshaping -> reshape an input tensor to a defined shape
* View -> Return a view of an input tensor of certain shapw but keep the same memory as the original tensor
* Stacking -> Combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze -> removes all `1` dimentions from a tensor
* unsqueeze -> add a `1` dimentions to a target tensor
* permute -> return a view of the input with dimention permuted(swapped) in a certain way

In [53]:
#Create tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
#Add a extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [55]:
#change the view
z = x.view(3,3)
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [56]:
#Chaning z changes x (because view shares the same memory)
z[:,0]=5
x,z

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]),
 tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]))

In [57]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0) #0 horizontal stack ,1 is veritical stack
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [58]:
#torch.squeeze()
x_reshaped2 = x_reshaped.reshape(1,9)
x_squeezed = x_reshaped2.squeeze()
x_reshaped2,x_reshaped2.ndim,x_reshaped2.squeeze().ndim,x_reshaped2.squeeze()

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]),
 2,
 1,
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [59]:
#torch.unsqueeze()
x_unsqueeze = x_squeezed.unsqueeze(dim=0)
x_unsqueeze,x_unsqueeze.shape,x_unsqueeze.ndim

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]), 2)

In [60]:
#torch.permute, like view uses the same memory location
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

##Indexing(selecting data from tensors)

In [61]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
#Let's index on the middle bracket(dim=1)
x[0][1]
x[0,1]

tensor([4, 5, 6])

In [64]:
#Lets index on the most inner bracket (last dim)
x[0,0,0]

tensor(1)

In [65]:
x[0,2,2]

tensor(9)

In [66]:
x[:,2,2]

tensor([9])

In [67]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and numpy
* Data in numpy to torch `torch.from_numpy(ndarray)`
* Pytorch tensor -> numpy functionality -> `torch.Tensor.numpy()`

In [68]:
#numpy array to tensor #default dtype in numpy is float64
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [69]:
#change the value of the array
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [70]:
#Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor,numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

##Reproducibility Random out of random, flavour randomness

In [71]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Check for GPU access with pytorch

In [72]:
#check GPU in pytorch
import torch
torch.cuda.is_available()

True

In [73]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [74]:
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [78]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

##Moving tensors back to the CPU

In [81]:
tensor_on_gpu.numpy()

TypeError: ignored

In [83]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

#All Video Completed **proceed  to exercise**

